apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - log-output/log-output-deployment.yaml
  - log-output/log-output-service.yaml
  - log-output/log-output-configmap.yaml
  - pingpong/pingpong-deployment.yaml
  - pingpong/pingpong-service.yaml
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - ingress.yaml

images:
  - name: alketaz/pingpong
    newName: us-central1-docker.pkg.dev/pingpong-logging/pingpong-logging/pingpong
    newTag: latest
  - name: alketaz/log-output
    newName: us-central1-docker.pkg.dev/pingpong-logging/pingpong-logging/log-output
    newTag: latest
