apiVersion: v1
kind: Service
metadata:
  name: log-output-service
  namespace: my-project
spec:
  type: NodePort             
  selector:
    app: log-output
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081
