apiVersion: v1
kind: Service
metadata:
  name: pingpong-service
  namespace: my-project
spec:
  type: NodePort                
  selector:
    app: pingpong
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
