name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: pingpong-cluster
  GKE_ZONE: us-central1-a
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      # --- Build and Push pingpong ---
      - name: Build pingpong Docker image
        run: docker build -t "us-central1-docker.pkg.dev/$PROJECT_ID/pingpong-logging/pingpong:$BRANCH-$GITHUB_SHA" ./pingpong

      - name: Push pingpong Docker image
        run: docker push "us-central1-docker.pkg.dev/$PROJECT_ID/pingpong-logging/pingpong:$BRANCH-$GITHUB_SHA"

      # --- Build and Push log-output ---
      - name: Build log-output Docker image
        run: docker build -t "us-central1-docker.pkg.dev/$PROJECT_ID/pingpong-logging/log-output:$BRANCH-$GITHUB_SHA" ./log-output

      - name: Push log-output Docker image
        run: docker push "us-central1-docker.pkg.dev/$PROJECT_ID/pingpong-logging/log-output:$BRANCH-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy to GKE
        run: |
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment pingpong-deployment -n my-project
          kubectl rollout status deployment log-output -n my-project
          kubectl get services -n my-project -o wide
