# .github/workflows/main.yaml
name: Release application

on:
  push:
    branches:
      - main

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest

    # these come from your GitHub Secrets
    env:
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      REGION: us-central1
      GKE_CLUSTER: pingpong-cluster
      GKE_ZONE: us-central1-a
      REPO_PING: pingpong
      REPO_LOG: log-output

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Authenticate to GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      # 3️⃣ Install the Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 4️⃣ Configure Docker → Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud --quiet auth configure-docker $REGION-docker.pkg.dev

      # 5️⃣ Build & push pingpong image
      - name: Build & Publish pingpong
        run: |
          IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_PING/$REPO_PING:$GITHUB_REF_NAME-$GITHUB_SHA
          echo "Building $IMAGE"
          docker build -t "$IMAGE" pingpong
          docker push "$IMAGE"

      # 6️⃣ Build & push log-output image
      - name: Build & Publish log-output
        run: |
          IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_LOG/$REPO_LOG:$GITHUB_REF_NAME-$GITHUB_SHA
          echo "Building $IMAGE"
          docker build -t "$IMAGE" log-output
          docker push "$IMAGE"

      # 7️⃣ Fetch GKE credentials
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location:     ${{ env.GKE_ZONE }}
          project_id:   ${{ env.PROJECT_ID }}

      # 8️⃣ Deploy pingpong
      - name: Deploy pingpong
        run: |
          IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_PING/$REPO_PING:$GITHUB_REF_NAME-$GITHUB_SHA
          kubectl set image deployment/pingpong-deployment \
            pingpong="$IMAGE"
          kubectl rollout status deployment/pingpong-deployment

      # 9️⃣ Deploy log-output
      - name: Deploy log-output
        run: |
          IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_LOG/$REPO_LOG:$GITHUB_REF_NAME-$GITHUB_SHA
          kubectl set image deployment/log-output \
            log-output="$IMAGE"
          kubectl rollout status deployment/log-output
